server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

services:
  users:
    url: http://localhost:8082

spring:
  datasource:
    # Эти свойства будут перегружены свойствами в docker-compose.yml
    url: jdbc:postgresql://localhost:5433/library
    username: library_user
    password: library_pass
  jpa:
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
  liquibase:
    enabled: true