server:
  port: 8082

spring:
  datasource:
    # Эти свойства будут перегружены свойствами в docker-compose.yml
    url: jdbc:postgresql://localhost:5434/users
    username: users_user
    password: users_pass
  jpa:
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
  liquibase:
    enabled: true

jwt:
  keys:
    private: classpath:app.key
    public: classpath:app.pub
  expiration: 36000 # seconds