spring:
  datasource:
    url: jdbc:h2:mem:maindb
  jpa:
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
  jmx:
    enabled: true

logging:
  file:
    name: hw16.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true