version: '3'
services:
  app-library:
    build:
      context: ./library
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5433/library
      - SPRING_DATASOURCE_USERNAME=library_user
      - SPRING_DATASOURCE_PASSWORD=library_pass

  # TODO port and users url from configuration
  # TODO keys from configuration for users

  app-users:
    build:
      context: ./users
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5434/users
      - SPRING_DATASOURCE_USERNAME=users_user
      - SPRING_DATASOURCE_PASSWORD=users_pass

  app-frontend:
    build:
      context: ./frontend
    environment:
      - PORT=8080
    network_mode: host

  postgres_library:
    image: "postgres:13"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=library_pass
      - POSTGRES_DB=library

  postgres_users:
    image: "postgres:13"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=users_user
      - POSTGRES_PASSWORD=users_pass
      - POSTGRES_DB=users

