version: '3'
services:
  app-library:
    build:
      context: ./library
    ports:
      - "8081:8081"
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-library:5432/library
      - SPRING_DATASOURCE_USERNAME=library_user
      - SPRING_DATASOURCE_PASSWORD=library_pass
      - SERVICES_USERS_URL=http://app-users:8082
      - SERVICES_MINIO_URL=http://minio:9000
      - MINIO_USER=minioadmin
      - MINIO_PASSWORD=miniopass

  app-users:
    build:
      context: ./users
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-users:5432/users
      - SPRING_DATASOURCE_USERNAME=users_user
      - SPRING_DATASOURCE_PASSWORD=users_pass

  app-frontend:
    build:
      context: ./frontend
    environment:
      - PORT=8080
    network_mode: service:app-library

  postgres-library:
    image: "postgres:13"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=library_pass
      - POSTGRES_DB=library

  postgres-users:
    image: "postgres:13"
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=users_user
      - POSTGRES_PASSWORD=users_pass
      - POSTGRES_DB=users

  minio:
    build:
      context: ./minio
    ports:
      - "9000:9000"
      - "9001:9001"  # Management Console Port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopass
    volumes:
      - minio-data:/data

volumes:
  minio-data: {}
